name = "CStarSurfaces"
uuid = "d9e57b9c-945c-49a8-a633-a7fe926ee407"
authors = ["Justus Springer <justusspringer@gmx.de>"]
version = "1.0.0-thesis"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RationalPolygons = "d26dedfb-ad13-44bd-90c7-a2710fa2c005"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
LinearAlgebra = "1.11.0"
RationalPolygons = "1.1.0"
StaticArrays = "1.9.8"
Test = "1.11.0"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CSV", "DataFrames"]
